### ISSUE TITLE
Have you droped this app?

### ISSUE THREAD

**Issue by RunningCl0ud** [aleung/RunningCadence#3]
@aleung 
Do you still work on this app?
I ask because I am using RunnerUp(imo a very good app for runners) but they have no support for cadence yet and if you got that working maybe you can bring some knowledge to the project?
Thank you. 
/RunningCl0ud
https://github.com/jonasoreland/runnerup/issues/24

**Comment by aleung** [comment]
@RunningCl0ud 
I have no plan to add feature on this app.
I will be happy if my code benefits other open source project. So just feel free to use my code. I license it under Apache License.
You may contact me via leoliang@gmail.com for question to my code.

**Comment by aleung** [comment]
I wrote a blog article about how this app measures foot strike by accelerometer equipped on mobile phone. It's in Chinese and perhaps you can read it with help from Google translate.

http://aleung.github.io/blog/2011/12/24/Running-training-software-development-XiaoJi-RunningCadence-step-frequency/

**Comment by RunningCl0ud** [comment]
Thank You! I think I understand the most of it. :+1:
